### ISSUE TITLE
Headers added by PR #12 break iframes

### ISSUE THREAD

**Issue by jacobwgillespie** [cloudflare/worker-sites-init#13]
It appears that PR #12 adds an `X-Frame-Options` header set to `DENY`. We are currently using Cloudflare Sites to publish an internal React Storybook, and Storybook renders stories inside iframes, so this change has broken those deployments.

Would it be possible to make this header configurable in the `wrangler.toml`? We previously just set `sites = "path/to/public/dir"` to publish the site, but it doesn't look like there's a way to override this new header in the Wrangler config.

**Comment by oscargm** [comment]
I'm experiencing the same issue.

This configuration is too restrictive by default and there's no way to override this.
We managed a solution changing the worker code and changing `DENY` to `same-origin` but in each deploy this would be overriden.

Would be great to be able to configure this using `wrangler publish --params` or being able to choose templates and having one that allow different `X-Frame-Options`values

**Comment by xortive** [comment]
This repo is a template for new projects, and the headers serve as reasonable defaults.

You should just be able to remove the headers from `workers-site/index.js` after using `wrangler init --site` or `wrangler generate --site`.

**Comment by jacobwgillespie** [comment]
I might be missing something here, but I only have a `wrangler.toml` alongside my public directory, and am able to deploy in CI with just that, running `wranger publish`. I don't have a `workers-site/index.js` to edit.

My `wrangler.toml` looks like:

```toml
name = "xxxxxx"
type = "javascript"
workers_dev = false
route = "example.com/*"
zone_id = "xxxxxx"
account_id = "xxxxxx"

[site]
bucket = "public"
```

**Comment by xortive** [comment]
@jacobwgillespie Ah, had to take a peek at the sites implementation to see what's going on.

You can run `wrangler init --site` inside of your project locally, which will then put the site worker code inside of your project (in the `workers-site` directory). This is exactly what `wrangler publish` is doing for you in CI every time your project is deployed. If `wrangler` sees that this has already been done, it will skip that step and use the code inside of `workers-site/index.js`.

Did you read documentation somewhere that indicated you should setup your project this way? I'd like to get that changed if so -- recommending unpinned dependencies in CI by default tends to cause problems like this.

**Comment by jacobwgillespie** [comment]
Interesting, that explains it somewhat... It's been a while since I've read the documentation in detail, so not sure if this is something I picked up from someplace specific there.

To be a bit more clear about my use-case, I have an internal custom GitHub Action that publishes a static site in a directory to Cloudflare as a Cloudflare Site. The action already contains a copy of `wrangler`, installed via NPM. So consumers inside our org can add an action to their projects to publish, without needing to know anything about Cloudflare/Wranger. Something like this (simplified):

```yaml
steps:
  - uses: org/publish-cloudflare-site
    with:
      dir: path/to/public
      domain: site.example.com
```

Then internally inside the action, it writes a `wrangler.toml` to disk, filling in the details, and calls `wrangler publish`.

My immediate fix is probably having the action also pre-generate the `workers-site/index.js` as well.

That said, it would also be cool for Wranger to have a way to publish a directory of static files as a site, without needing a ton of extra config. The only very important config bits are just the directory of files and the target route after all. It kinda has this now, by simply running `wrangler publish`, besides this issue with the header change, but I understand that wasn't entirely intentional.

**Comment by xortive** [comment]
I think your use case is exactly what we're aiming at with [Cloudflare Pages](https://pages.cloudflare.com/), which is now in open beta :)

**Comment by oscargm** [comment]
> This repo is a template for new projects, and the headers serve as reasonable defaults.
> 
> You should just be able to remove the headers from `workers-site/index.js` after using `wrangler init --site` or `wrangler generate --site`.

I saw the headers that are the root of the problem in the `workers-site/index.js`, that's why I landed here

> You can run `wrangler init --site` inside of your project locally, which will then put the site worker code inside of your project (in the `workers-site` directory). This is exactly what `wrangler publish` is doing for you in CI every time your project is deployed. If `wrangler` sees that this has already been done, it will skip that step and use the code inside of `workers-site/index.js`.

What I didn't know is that wrangler would skip overwriting the file. 
We didn't include the workers-site in our repository as I thought that was something temporal wrangler needed, didn't give more importance.

> I think your use case is exactly what we're aiming at with [Cloudflare Pages](https://pages.cloudflare.com/), which is now in open beta :)

Looks like pages need to be linked to github, there's no option to use any other scm like Gitlab?

Anyway, looks I can continue my journey after reading the replies, thanks @xortive for all the info

**Comment by jacobwgillespie** [comment]
> I think your use case is exactly what we're aiming at with [Cloudflare Pages](https://pages.cloudflare.com/), which is now in open beta :)

This isn't quite what we're going for - you could think of it as pull vs push, where Cloudflare Pages is a pull model, as Cloudflare connects to your repo, pulls in source code, runs builds, and publishes the result. Instead we have a push model, where we have a static site artifact produced in CI, and we want to push those files to a Cloudflare Site. There's not a 1-1 mapping between repos and published sites, and we have to build the sites as part of a larger monorepo pipeline that wouldn't fit into the model of Cloudflare Pages.

---

Pre-generating the `workers-site/index.js` is working perfectly, we're able to modify the headers there and publish our Storybook sites again. Thanks for the pointer!

Closing this issue...

**Comment by ustincameron** [comment]
Hi, I'm using both wrangler workers and cloudflare pages but both are forcing the DENY header. Even when changing `workers-site/index.js` locally, the header still appears on deploy.

Any suggestions?
